/* This file is automatically generated by uprev. Do not edit. */

#define VERSION        3
#define REVISION        20
#define PATCH         1
#define DATE    "1.9.2026"
#define VERS    "DC1 3.20.1"
#define VSTRING "DC1 3.20.1 (1.9.2026)"
#define VERSTAG "\0$VER: DC1 3.20 (1.9.2026)"
