/* This file is automatically generated by uprev. Do not edit. */

#define VERSION        3
#define REVISION        20
#define PATCH         0
#define DATE    "22.3.2026"
#define VERS    "flush 3.20.0"
#define VSTRING "flush 3.20.0 (22.3.2026)"
#define VERSTAG "\0$VER: flush 3.20 (22.3.2026)"
