/* This file is automatically generated by uprev. Do not edit. */

#define VERSION        3
#define REVISION        20
#define PATCH         0
#define DATE    "25.1.2026"
#define VERS    "dmake 3.20.0"
#define VSTRING "dmake 3.20.0 (25.1.2026)"
#define VERSTAG "\0$VER: dmake 3.20 (25.1.2026)"
