/* This file is automatically generated by uprev. Do not edit. */

#define VERSION        3
#define REVISION        20
#define PATCH         0
#define DATE    "23.1.2026"
#define VERS    "VOpts 3.20.0"
#define VSTRING "VOpts 3.20.0 (23.1.2026)"
#define VERSTAG "\0$VER: VOpts 3.20 (23.1.2026)"
